---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: moderngaming-live-proj-logging
spec:
  schedule: 1 0 * * *
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: quay.io/pires/docker-elasticsearch-curator:5.5.4
            args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
