apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: es-data
  namespace: zerbytes-live-proj-logging
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: data
