---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pv-claim
  labels:
    app: busybox
spec:
  storageClassName: rook-blk-r1-s2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
