apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-cool-app
  labels:
    app: wordpress
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
